### PR TITLE
MBMicro

### PR DESCRIPTION
**Pull request by openmb**

### CODE REVIEW

**Comment by atvcaptain** [comment]
sorry make a clean merge request and not test test test

**Comment by openmb** [comment]
It is only Picture and it use same RCU like other models.

7000S has wrong rcu I think and thats why We make test.

I can not make other request because commits are there already :(

**Comment by atvcaptain** [comment]
i check this and add this to branding

**Comment by openmb** [comment]
Great. Thanks. Please keep in touch with paul also

**Pull request closed without merging**
